import PartidoCard from '../components/cards/PartidoCard'

export default function PartidosPage({
  partidos = [
    {
      id: 1,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
    {
      id: 2,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
    {
      id: 3,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
    {
      id: 4,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
    {
      id: 5,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
    {
      id: 6,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
    {
      id: 7,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
    {
      id: 8,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
    {
      id: 9,
      date: '12/5/26 10:00',
      player1: 'Wayne Rooney',
      player2: 'Roger',
      player3: 'Yonatan',
      player4: 'Abdeselem',
      set1_score_team1: 6,
      set1_score_team2: 4,
      set2_score_team1: 6,
      set2_score_team2: 4,
      set3_score_team1: 6,
      set3_score_team2: 4,
    },
  ],
}) {
  return (
    <section className="flex flex-wrap justify-center gap-8">
      {partidos.map((p) => (
        <PartidoCard key={p.id} partido={p} />
      ))}
    </section>
  )
}
